# Default values for vineyard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: vineyardcloudnative/vineyardd
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tagPrefix: ""
  tag: ""

metricImage:
  repository: vineyardcloudnative/vineyardd-grok-exporter
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tagPrefix: ""
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 9600

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

affinity: {}

vineyard:
  sharedMemorySize: ""

  # volumeType controls the type of UNIX-domain socket volume, can
  # be either "persistentVolumeClaim" or "hostPath"
  volumeType: hostPath
  size: 1Mi

  # Synchronize CRDs when persisting objects
  syncCRDs: ""

  # PVC name if volume type is persistentVolumeClaim
  persistVolumeClaimName: "vineyard-domain-socket"
  accessModes:
    - ReadWriteOnce
  storageClass: standard

  # host path if volume type is "hostPath", the default value will be
  #
  #   /var/run/vineyard-{{ .Release.Namespace }}-{{ include "vineyard.fullname" . }}
  hostPath: ""

  # Whether to print metrics for prometheus or not.
  metrics: False
  
serviceAccountName: ""

tolerations: {}
  # this toleration is to have the daemonset runnable on master nodes
  # remove it if your masters can't run pods.
  # - key: node-role.kubernetes.io/master
  #   effect: NoSchedule

env:
  {}
