# referred from https://github.com/etcd-io/etcd/blob/master/hack/kubernetes-deploy/etcd.yml

apiVersion: v1
kind: Service
metadata:
  name: etcd-for-vineyard
  namespace: {{ .Namespace }}
spec:
  ports:
  - name: etcd-for-vineyard-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd