# Copyright 2020 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Vineyardd Binary

on:
  push:
  pull_request:
    paths:
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'src/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Login docker registry
        if: runner.os == 'Linux'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

      - name: Build vineyardd on Linux
        if: runner.os == 'Linux'
        run: |
          sudo docker build . -f docker/Dockerfile.vineyardd -t docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-${{ github.sha }}
          sudo docker run --rm -v `pwd`:/target docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-${{ github.sha }} sh -c "cp /usr/bin/vineyardd /target/"
          ldd ./vineyardd

      - name: Package vineyardd artifact on Linux
        if: runner.os == 'Linux'
        run: |
          sha512sum ./vineyardd > vineyardd.${{ github.sha }}.sha512sum
          echo "Checksum is: "
          cat ./*.sha512sum
          tar zcvfh vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz ./vineyardd vineyardd.${{ github.sha }}.sha512sum

      - name: Upload docker image
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'alibaba/libvineyard' }}
        run: |
          sudo docker tag docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-${{ github.sha }} \
                          docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-latest
          sudo docker tag docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-${{ github.sha }} \
                          docker.pkg.github.com/alibaba/libvineyard/vineyardd:latest

          sudo docker push docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-${{ github.sha }}
          sudo docker push docker.pkg.github.com/alibaba/libvineyard/vineyardd:alpine-latest
          sudo docker push docker.pkg.github.com/alibaba/libvineyard/vineyardd:latest

      - name: Upload wheels to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'alibaba/libvineyard' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          asset_name: vineyardd-latest-linux_x86-64.tar.gz
          tag: latest
          prerelease: true
          overwrite: true
          body: "Prerelease for latest vineyard"

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
          path: vineyardd.${{ runner.os }}-generic.${{ github.sha }}.tar.gz
